### ISSUE TITLE
Nonfunctional translucent menu buttons + Dustbowl background 

### ISSUE THREAD

**Issue by OneTrueLlamaGod** [TechnoSL/middle-mann-tf2c#2]
Opening the game after the hud's most recent update leaves the main menu nonfunctional, with the default dustbowl rocket background overlayed on top of of the typical TF2 classic backgrounds. None of the buttons are interactable after loading, however joining a server without using the main menu fixes the issue upon returning.

![MiddleMannMainMenuGlitch](https://github.com/TechnoSL/middle-mann-tf2c/assets/89337463/85d52c5b-4c15-4338-a9d2-640ae76ad771)

**Comment by tekunotri** [comment]
is the game simply frozen between transitioning into the main menu?
any other mods you might be using besides the hud?

i'll try looking into it when i have the time

**Comment by ajaxxxxxxx** [comment]
I also have this issue, a temp fix is opening console and going into an itemtest server. Buttons and menu will work after.

**Comment by tekunotri** [comment]
> is the game simply frozen between transitioning into the main menu? any other mods you might be using besides the hud?
> 
> i'll try looking into it when i have the time

after 3 months i... still can't recreate this issue on my end

**Comment by Polarite** [comment]
I have same issue, still happening.

**Comment by tekunotri** [comment]
ok, theory might be that it's due to valve.rc most likely, can you comment out this line https://github.com/TechnoSL/middle-mann-tf2c/blob/main/cfg/valve.rc#L11 and see if it works?

**Comment by Polarite** [comment]
![image](https://github.com/TechnoSL/middle-mann-tf2c/assets/34978332/932a5645-12d9-46cb-bf47-66bf54f114ee)
similar issue mentioned here.

**Comment by tekunotri** [comment]
ok, if so it's definetly startupmenu, i'll make a commit and ask for a redownload

**Comment by tekunotri** [comment]
https://github.com/TechnoSL/middle-mann-tf2c/releases/tag/1.1.2 please retest (seemed to fix it on my end)
