### ISSUE TITLE
ubercharge, energy melee and healing overlap

### ISSUE THREAD

**Issue by Polarite** [TechnoSL/middle-mann-tf2c#3]
![image](https://github.com/TechnoSL/middle-mann-tf2c/assets/34978332/23d453f8-bb5f-44f4-8e82-b9df5781f1b8)

**Comment by tekunotri** [comment]
already in the todo list #1 will fix later

**Comment by tekunotri** [comment]
fixed as of commit [35b3682](https://github.com/TechnoSL/middle-mann-tf2c/commit/35b36827274a957cc2b9ca8c8edd58c39733140c)

closing
